In [1]:
import torch
from torch import nn

In [3]:
# 对图像标准化，num_features参数指定了要标准化的通道数.这个值等于图像的通道数
bn1 = nn.BatchNorm2d(num_features=3)

In [8]:
img = torch.randn(1, 3, 6, 6)
img

tensor([[[[ 1.0407, -0.9431, -1.4498, -0.1065, -0.3345,  0.1026],
          [-1.2675, -0.6724, -0.1131, -0.4909,  0.7564,  1.5402],
          [-0.3508,  1.7246,  0.8754, -0.4130,  0.5807, -0.2061],
          [ 0.1287,  0.1674, -1.0641, -1.2509,  0.1818, -0.2809],
          [-1.7824, -0.2628,  1.6266, -0.8584, -0.5639,  0.8420],
          [ 0.1751,  1.3750,  2.2076, -0.0294, -1.1358,  0.8510]],

         [[ 0.0396,  0.7924,  0.5340,  1.2165, -1.4462, -1.1211],
          [-0.6878, -0.1835,  2.2004,  0.5044, -0.9465, -0.2491],
          [-0.8234, -0.3345, -1.7889, -0.2881,  1.7871, -0.3805],
          [-0.3364, -0.7443, -0.2413, -0.7700, -0.0221,  0.7679],
          [-0.3363, -1.0482, -1.1866,  0.5071, -0.1461,  0.7177],
          [-1.0356,  0.2760,  0.1934,  1.4851, -0.5150,  1.0232]],

         [[-0.7261, -1.0866,  1.3225,  0.2018, -0.2483,  0.9407],
          [ 1.6058,  0.9725, -1.3700, -1.0168, -0.6532,  0.5865],
          [ 0.9734, -1.5879, -0.8249,  0.0540, -0.3647, -1.2443],
      

In [11]:
# 标准化之后的结果
r = bn1(img)
r

tensor([[[[ 1.0666, -0.9996, -1.5273, -0.1282, -0.3658,  0.0895],
          [-1.3375, -0.7177, -0.1351, -0.5287,  0.7704,  1.5868],
          [-0.3827,  1.7788,  0.8943, -0.4475,  0.5874, -0.2320],
          [ 0.1167,  0.1570, -1.1256, -1.3201,  0.1720, -0.3099],
          [-1.8737, -0.2911,  1.6768, -0.9113, -0.6046,  0.8596],
          [ 0.1650,  1.4147,  2.2818, -0.0480, -1.2003,  0.8690]],

         [[ 0.1230,  0.9539,  0.6687,  1.4219, -1.5168, -1.1580],
          [-0.6798, -0.1232,  2.5078,  0.6360, -0.9653, -0.1957],
          [-0.8295, -0.2899, -1.8951, -0.2387,  2.0517, -0.3407],
          [-0.2920, -0.7421, -0.1870, -0.7705,  0.0549,  0.9267],
          [-0.2919, -1.0775, -1.2302,  0.6390, -0.0820,  0.8714],
          [-1.0636,  0.3840,  0.2928,  1.7184, -0.4891,  1.2085]],

         [[-0.7845, -1.1622,  1.3616,  0.1875, -0.2840,  0.9615],
          [ 1.6582,  0.9949, -1.4590, -1.0891, -0.7081,  0.5905],
          [ 0.9958, -1.6873, -0.8880,  0.0327, -0.4059, -1.3274],
      

In [10]:
r

tensor([[[[ 1.0666, -0.9996, -1.5273, -0.1282, -0.3658,  0.0895],
          [-1.3375, -0.7177, -0.1351, -0.5287,  0.7704,  1.5868],
          [-0.3827,  1.7788,  0.8943, -0.4475,  0.5874, -0.2320],
          [ 0.1167,  0.1570, -1.1256, -1.3201,  0.1720, -0.3099],
          [-1.8737, -0.2911,  1.6768, -0.9113, -0.6046,  0.8596],
          [ 0.1650,  1.4147,  2.2818, -0.0480, -1.2003,  0.8690]],

         [[ 0.1230,  0.9539,  0.6687,  1.4219, -1.5168, -1.1580],
          [-0.6798, -0.1232,  2.5078,  0.6360, -0.9653, -0.1957],
          [-0.8295, -0.2899, -1.8951, -0.2387,  2.0517, -0.3407],
          [-0.2920, -0.7421, -0.1870, -0.7705,  0.0549,  0.9267],
          [-0.2919, -1.0775, -1.2302,  0.6390, -0.0820,  0.8714],
          [-1.0636,  0.3840,  0.2928,  1.7184, -0.4891,  1.2085]],

         [[-0.7845, -1.1622,  1.3616,  0.1875, -0.2840,  0.9615],
          [ 1.6582,  0.9949, -1.4590, -1.0891, -0.7081,  0.5905],
          [ 0.9958, -1.6873, -0.8880,  0.0327, -0.4059, -1.3274],
      