In [ ]:
# pytorch的安装
# 直接去官网，https://pytorch.org/get-started/locally/ 选择你的电脑配置，官方会给你一个安装命令，直接执行即可

In [ ]:
import torch

In [18]:
# 检测设备：cuda:0 表示使用cuda的第0个显卡
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cpu')

In [19]:
# 随机一个变量，3行2列；randn 其中的 n 表示normal distrubution 高斯分布
x1 = torch.randn(3,2)
x1

tensor([[-0.8029,  1.7867],
        [ 0.1402, -0.2735],
        [-0.3441, -0.0525]])

In [20]:
# 形状
x1.shape

torch.Size([3, 2])

In [21]:
# 类型
x1.dtype

torch.float32

In [22]:
# 维度
x1.ndim

2

In [23]:
# 转置
x1.T

tensor([[-0.8029,  0.1402, -0.3441],
        [ 1.7867, -0.2735, -0.0525]])

In [24]:
# 设备
x1.device

device(type='cpu')

In [25]:
# 是否需要计算梯度（求导）
x1.requires_grad

False

In [27]:
x2 = torch.randn(3,2,device=device)
x2

tensor([[-0.2826, -0.3188],
        [-1.3381,  1.0342],
        [-0.3415,  0.8029]])

In [28]:
# 因为我是mac，没有conda，如果x1和x2位于不同的device，是不能直接计算的。
x1 + x2

tensor([[-1.0855,  1.4679],
        [-1.1979,  0.7607],
        [-0.6855,  0.7504]])

In [33]:
# 变量在不同device之间转换，转换之后，就可以计算了。

# 第一种转换方式(不太常用)
x1.to(device='cpu')
# x2.to(device='cuda:0')

# 第二种转换方式（常用）
# x1.cuda()
x2.cpu()

# 转换完成之后，返回的都是一个新的张量

tensor([[-0.2826, -0.3188],
        [-1.3381,  1.0342],
        [-0.3415,  0.8029]])

In [34]:
# 计算
x1.requires_grad = True

In [35]:
x1

tensor([[-0.8029,  1.7867],
        [ 0.1402, -0.2735],
        [-0.3441, -0.0525]], requires_grad=True)

In [36]:
y = x1.sum()

In [37]:
y

tensor(0.4541, grad_fn=<SumBackward0>)

In [38]:
x1.grad

In [39]:
y.backward()

In [40]:
x1.grad

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [41]:
y.backward()

In [42]:
x1.grad

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [43]:
y.backward()

In [44]:
x1.grad

tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])

In [45]:
# 梯度不会清空，每次都是累计的。如果需要清空，则需要手动清空

In [47]:
# 针对一个张量，包括 data域 和 grad域
# 把data域置空
x1.data.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [48]:
# 但不影响 grad 域
x1.grad

tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])

In [49]:
x1.grad.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [50]:
x3 = torch.randn(3,2,requires_grad=True)

In [51]:
y = x3 ** 2
# 这个公式无法求导，因为 x3 是一个 3x2 的张量，那么平方之后的结果也是一个张量。也就相当于是有 3x2=6 的自变量和6个因变量
# 但是在数学中，一般自变量可以有多个，但是因变量只会有一个。也叫单值函数；但是上面的公式，不满足这个定义，所以导致求导报错
y.backward()

In [ ]:
# 求个平均值，结果就是一个标量了。
# 这个公式就是 y = (x3 ** 2) / 6
y = (x3 ** 2).mean()
y.backward()